// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMb0npYrE0QJhdy8WJHW7hxSfYbafKab4',
    appId: '1:509657310493:web:50681b0bbfaeb058faedf4',
    messagingSenderId: '509657310493',
    projectId: 'course-motobike-7141a',
    authDomain: 'course-motobike-7141a.firebaseapp.com',
    storageBucket: 'course-motobike-7141a.firebasestorage.app',
    measurementId: 'G-YQYT1RHVHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1tWRwTOH8MdfUH0jmOGzW2OOFD3ykuOg',
    appId: '1:509657310493:android:74e0a9db2e09a540faedf4',
    messagingSenderId: '509657310493',
    projectId: 'course-motobike-7141a',
    storageBucket: 'course-motobike-7141a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOw-NRI5EhSBguD4o-0_u0YCa1UXJX3aw',
    appId: '1:509657310493:ios:a15f36293256cafffaedf4',
    messagingSenderId: '509657310493',
    projectId: 'course-motobike-7141a',
    storageBucket: 'course-motobike-7141a.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOw-NRI5EhSBguD4o-0_u0YCa1UXJX3aw',
    appId: '1:509657310493:ios:a15f36293256cafffaedf4',
    messagingSenderId: '509657310493',
    projectId: 'course-motobike-7141a',
    storageBucket: 'course-motobike-7141a.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMb0npYrE0QJhdy8WJHW7hxSfYbafKab4',
    appId: '1:509657310493:web:4c08675876b53b37faedf4',
    messagingSenderId: '509657310493',
    projectId: 'course-motobike-7141a',
    authDomain: 'course-motobike-7141a.firebaseapp.com',
    storageBucket: 'course-motobike-7141a.firebasestorage.app',
    measurementId: 'G-QNCFJERL17',
  );
}
